### ISSUE TITLE
Linux Support 

### ISSUE THREAD

**Issue by Starkiller1St** [fmuecke/Ipponboard#64]
Gibt es einen technischen Grund (library, Framework,...) weshalb es nicht möglich ist das Board auf einem Linux System lauffähig ist?  Wäre es möglich als Build Ziel "einfach" ein Linux system zu definieren?

**Comment by r-bernhard** [comment]
Die Unterstützung mit Linux befindet sich im Pullrequest #63, der noch nicht in den Hauptstrang überführt wurde.
Unter https://gitlab.com/r_bernhard/Ipponboard befindet sich ein Fork dieses Ipponboards, der ein Kompilat für Redhat- und Debian-basierte Linuxsysteme bereitstellt. Idealerweise nutzt man dieselbe Linuxversion, unter der das Kompilat erstellt wurde (Rocky 9.3 und Lubuntu 22.04).  In der Readme des Forks befindet sich auch ein Link zum Download eines 32/64 bit Windows- und eines 32bit Linux Kompilats (Linux Mint Debian Edition 5)

**Comment by fmuecke** [comment]
@Starkiller1St der aktuelle Stand auf dem main-Branch baut jetzt unter Linux. Es funktioniert sicher noch nicht alles, aber schon das meiste. Im Fork von @r-bernhard geht sicher schon mehr. Ich werde versuchen das ein oder andere hierhin zu übernehmen.
